name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      # TODO: switch to "nimble install nimble" after nimble v1 release
      nimble-version: 42ef70c2102a942c46f13eb76872326edd525cec # v0.22.3
      # env NIMLANG=cpp nimble test
      test-command: |
        nimble dump --solve
        nimble list --installed --version
        env nimble features
        env NIMLANG=c nimble test
        env NIMLANG=cpp nimble test
        env nimble examples
