name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: status-im/nimbus-common-workflow/.github/workflows/common.yml@main
    with:
      nim-versions: '["version-2-0", "version-2-2", "devel"]'
      nimble-version: HEAD
      test-command: |
        env nimble features
        env NIMLANG=c nimble test
        env NIMLANG=cpp nimble test
        env nimble examples
