name: Linters

on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nph:
    name: NPH
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check `nph` formatting
        uses: arnetheduck/nph-action@v1
        with:
          version: 0.6.1
          options: "."
          fail: true
          suggest: true
